name: gsheets
description:
  A library for working with Google Sheets API v4.
  Manage your spreadsheets with gsheets in Dart.
version: 0.4.2
homepage: https://github.com/a-marenkov/gsheets
repository: https://github.com/a-marenkov/gsheets.git
issue_tracker: https://github.com/a-marenkov/gsheets/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.0
  http: ^0.13.0
  meta: ^1.3.0
  collection: ^1.15.0
  babylonjs_viewer: ^1.2.1
  model_viewer: ^0.0.0
  fluttertoast: ^8.2.1
  fluentui_system_icons: ^1.1.200
  analog_clock: ^0.1.0

dev_dependencies:
  pedantic: ^1.11.1
  flutter_test:
    sdk: flutter
  test: ^1.19.5
flutter:


  uses-material-design: true